name: Add Two Numbers on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  add_numbers:
    if: github.event.pull_request.merged == true && github.base_ref == 'master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Numbers (Example)
        run: |
          NUM1=5  # Replace with dynamic extraction if needed
          NUM2=10 # Replace with dynamic extraction if needed
          echo "NUM1=$NUM1" >> $GITHUB_ENV
          echo "NUM2=$NUM2" >> $GITHUB_ENV

      - name: Add Numbers
        run: echo "RESULT=$(( $NUM1 + $NUM2 ))" >> $GITHUB_ENV

      - name: Display Result
        run: echo "The sum is $RESULT"
