name: Print four.py on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  print_four_py:
    if: github.event.pull_request.merged == true && github.base_ref == 'master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full commit history is available

      - name: Check if four.py was modified
        id: check_file
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "^four.py$"; then
            echo "FILE_CHANGED=true" >> $GITHUB_ENV
          else
            echo "FILE_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Exit if four.py was not changed
        if: env.FILE_CHANGED != 'true'
        run: echo "four.py not changed, skipping job." && exit 0

      - name: Print four.py Content
        run: cat four.py
