name: Add Two Numbers on four.py Merge

on:
  pull_request:
    types:
      - closed

jobs:
  add_numbers:
    if: |
      github.event.pull_request.merged == true &&
      github.base_ref == 'master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if four.py was modified
        id: check_file
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "^four.py$"; then
            echo "FILE_CHANGED=true" >> $GITHUB_ENV
          else
            echo "FILE_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Exit if four.py was not changed
        if: env.FILE_CHANGED != 'true'
        run: echo "four.py not changed, skipping job." && exit 0

      - name: Extract Numbers from four.py
        id: extract_numbers
        run: |
          NUM1=$(grep -oP '(?<=NUM1\s*=\s*)\d+' four.py | head -n 1 || echo "0")
          NUM2=$(grep -oP '(?<=NUM2\s*=\s*)\d+' four.py | head -n 1 || echo "0")
          echo "NUM1=${NUM1:-0}" >> $GITHUB_ENV
          echo "NUM2=${NUM2:-0}" >> $GITHUB_ENV

      - name: Validate Numbers
        run: |
          if ! [[ "$NUM1" =~ ^[0-9]+$ ]] || ! [[ "$NUM2" =~ ^[0-9]+$ ]]; then
            echo "Error: NUM1 or NUM2 is not a valid number."
            exit 1
          fi

      - name: Add Numbers
        run: |
          RESULT=$(( NUM1 + NUM2 ))
          echo "RESULT=$RESULT" >> $GITHUB_ENV

      - name: Display Result
        run: echo "The sum is $RESULT"
